apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  creationTimestamp: null
  name: spring-sensors
spec:
  build:
    buildpacks: {}
    path: ../..
  ports:
  - name: main
    port: 8080
